"""Capa de enriquecimiento de ia_nest_extended."""

from .clients import CoreClient, CoreResult, DomainRouteResult, OllamaEmbedder
from .config import ExtendedConfig
from .consolidation import ConsolidationExecutor
from .embedders import FakeEmbedder
from .enrichment import EnrichResult, MemoryEnricher, RecallBundle
from .errors import (
    AliasedDeclarationError,
    AliasedTierError,
    CoreClientError,
    CoreConnectionError,
    CoreResponseError,
    EngramNotFoundError,
    ExtendedConfigError,
    InvalidConsolidationEventError,
    InvalidEmbeddingDimensionError,
    InvalidEngramError,
    InvalidMemoryTypeError,
    InvalidNamespaceError,
    InvalidRagInputError,
    OllamaConnectionError,
    OllamaEmbedderError,
    OllamaResponseError,
    RagError,
    RagSchemaError,
    ScopeViolationError,
    UnknownMemoryTypeError,
    UnsupportedWriteError,
    WriteAuthorityError,
)
from .models import (
    ConsolidationEvent,
    ConsolidationResult,
    ConsolidationTrigger,
    Engram,
    EngramStatus,
    EngramWrite,
    EntityProfile,
    MemoryClass,
    MemoryIdentity,
    MemoryKey,
    MemoryType,
    Principal,
    RagChunk,
    RagChunkWrite,
    RagIngestResult,
    RecallItem,
    RecallQuery,
    RetrievalMode,
    Scope,
)
from .registry import MemoryTypeRegistry, seed_memory_types
from .ranking import calculate_relevance
from .telemetry import TelemetryWriter

__all__ = [
    "AliasedDeclarationError",
    "AliasedTierError",
    "CoreClient",
    "CoreClientError",
    "CoreConnectionError",
    "CoreResponseError",
    "CoreResult",
    "DomainRouteResult",
    "ConsolidationEvent",
    "ConsolidationExecutor",
    "ConsolidationResult",
    "ConsolidationTrigger",
    "EnrichResult",
    "Engram",
    "EngramNotFoundError",
    "EngramStatus",
    "EngramWrite",
    "EntityProfile",
    "ExtendedConfig",
    "ExtendedConfigError",
    "FakeEmbedder",
    "InvalidEmbeddingDimensionError",
    "InvalidConsolidationEventError",
    "InvalidEngramError",
    "InvalidMemoryTypeError",
    "InvalidNamespaceError",
    "InvalidRagInputError",
    "MemoryClass",
    "MemoryEnricher",
    "MemoryIdentity",
    "MemoryKey",
    "MemoryType",
    "MemoryTypeRegistry",
    "OllamaConnectionError",
    "OllamaEmbedder",
    "OllamaEmbedderError",
    "OllamaResponseError",
    "Principal",
    "RagChunk",
    "RagChunkWrite",
    "RagError",
    "RagIngestResult",
    "RagSchemaError",
    "RecallBundle",
    "RecallItem",
    "RecallQuery",
    "RetrievalMode",
    "Scope",
    "ScopeViolationError",
    "TelemetryWriter",
    "UnknownMemoryTypeError",
    "UnsupportedWriteError",
    "WriteAuthorityError",
    "calculate_relevance",
    "seed_memory_types",
]
